# Generated by Django 5.0.6 on 2024-05-16 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('num_contrato', models.CharField(max_length=50)),
                ('num_ata', models.CharField(max_length=50)),
                ('num_processos_licitatorio', models.CharField(max_length=150)),
                ('modalidade', models.CharField(max_length=50)),
                ('num_modalidade', models.CharField(max_length=150)),
                ('objeto', models.TextField()),
                ('fornecedor', models.TextField()),
                ('cnpj_cpf', models.CharField(max_length=50)),
                ('valor_mensal', models.CharField(max_length=50)),
                ('valor_anual', models.CharField(max_length=50)),
                ('inicio_vigencia', models.DateField()),
                ('final_vigencia', models.DateField()),
                ('done', models.CharField(choices=[(0, 'vigente'), (1, 'nao vigente ')], max_length=55)),
                ('fiscal', models.CharField(max_length=50)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('tipo', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
