# Generated by Django 5.0.6 on 2024-05-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dppecontratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='done',
            field=models.IntegerField(choices=[(0, 'vigente'), (1, 'nao vigente ')], max_length=55),
        ),
    ]
