# Generated by Django 5.0.6 on 2024-05-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dppecontratos', '0003_alter_contrato_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='objeto',
            new_name='objeto',
        ),
    ]
